host:
  transport:
    protocol: UTP
    address: 127.0.0.1:0
    behindnat: false
  bootstraphosts: []
  isrelay: false
  infinitybootstrap: false
  timeout: 4
node:
  node:
    id: "3vwhxni49TBGpj4CHLY5BRnmqeLfeDeCyeo1oW1ahMCXXc5eetzLwKFQqL8ycdp724W93QxV8aY9FbuSY5aky1QA"
service:
  service: {}
ledger:
  storage:
    datadirectory: ./data
    txretriesonconflict: 3
  jetcoordinator:
    rolecounts:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1

log:
  level: Debug
  adapter: logrus
stats:
  listenaddress: 0.0.0.0:8080
logicrunner:
  rpclisten: 127.0.0.1:18182
  builtin: {}
  goplugin:
    runnerlisten: 127.0.0.1:18181
pulsar:
  type: tcp
  listenaddress: 0.0.0.0:8090
  nodesaddresses: []
genesis:
  rootkeys: "../testdata/functional/root_member_keys.json"
  rootbalance: 10000
keyspath: "../testdata/functional/bootstrap_keys.json"
certificatepath: "../testdata/functional/certificate.json"

